#Entlc_to_KG.R 
#Process input file names, call routine to generate Koeppen-Geiger map from Ent cover fraction maps, output netCDF file of KG map, and plot.
args = commandArgs(trailingOnly=TRUE)
print(paste('args:', args))
numargs = length(args)
if (numargs < 1) {
cat ('Usage:  Rscript Entlc_to_KG.R <entlc> <kglut> <id>' )
cat('Config file must have:')
cat ('entlc: NetCDF file name of Ent land cover fractions EntGVSD_PFTs (18 cover types, including bright and dark soil), in format of ModelE VEG input file.' )
cat ('kglut: NetCDF file name of Koeppen-Geiger lookup table of format in R (kgn, lcn)=(40, 18) from "lc" array generated by Ent_utils/kglut_modelE programs.' )
cat ('id <Identifier for output file>' )
cat('Outputs to default "output" directory.')
quit()
}

Rpath = paste0(Sys.getenv("R_Ent"), "/")
if (Rpath=="") {
  cat("Please set environment variable R_Ent to the path to your Rfiles directory")
  quit()
}

source(paste0(Rpath, "/utils_noSDMTools.R"))
source(paste0(Rpath, "/KoeppenGeiger.R"))

configfile = args[1]
textin = readLines(con=configfile, n=8)
#pathin = paste(strsplit(textin[3], " ")[[1]][2], "/")

top=1
fileentlc = strsplit(readLines(con=configfile, n=top)[[top]]," ")[[1]][2]
filekglut = strsplit(readLines(con=configfile, n=top+1)[[top+1]]," ")[[1]][2]
id = strsplit(readLines(con=configfile, n=top+2)[[top+2]]," ")[[1]][2]
#fileentlc = args[1]
#filekglut = args[2]
#id = args[3]

if (!dir.exists("output")) {
        dir.create("output")
}

print(fileentlc)
print(filekglut)

kgmap = Entlc_to_KG(fileentlc, filekglut)
IM = nrow(kgmap); JM = ncol(kgmap)

tempstr = strsplit(fileentlc, "/")[[1]]
fnamelc = tempstr[length(tempstr)]
tempstr = strsplit(filekglut ,"/")[[1]]
fnamekg = tempstr[length(tempstr)]

fnameout = paste0("output/", "KG", res.from.IM.JM(IM,JM), "from_Entlc_", id)
write.KoeppenGeiger.netcdf(kgmap, fname=paste0(fnameout, ".nc"), varname="KG", undef=-1e30, description=paste0("Koeppen-Geiger classes derived from ",fnamelc, "and", fnamekg))

pdf(file=paste0(fnameout, ".pdf"), width=9.6, height=6)
plot.KG(kgmap, if.new=TRUE)


