#KG_run_template.R

#########################
#			#
# DO NOT EDIT THIS FILE #
#			#
#########################

source("utils_noSDMTools.R")
source("KoeppenGeiger.R")
library(rworldmap)

#Offline, make your input files:
#Temperature and precip files should be netcdf files, each with a variable of dimension (IM, JM, 12) for monthly values.


#Generate the classification

KGnum = run.KG(Tnc="TEMPERATURE_DATA",
	Pnc="PRECIPITATION_DATA",
	Tname="tmp",
	Pname="prec",
	IM=I_ARRAY_LEN, JM=J_ARRAY_LEN,
	ttext="TEMPERATURE_DATA", 
	ptext="PRECIPITATION_DATA",
	if.new=FALSE)


#Plot again without having to generate the classification all over.
pdf("Rplots_KG.pdf", width=9.6, height=6)
par(omi=c(0,0,0,1)) #(bottom, left, top, right)
par(omi=c(0,0,0,0), oma=c(0,0,0,4)) #(bottom, left, top, right) #Use for single

plot.KG(KGnum, if.new=FALSE)
par(xpd=TRUE)
legend(-180, 112, legend=KGcat[1:20,"KGcode"],col=KGrgbhex[1:20], pt.cex=2, pch=15, cex=0.6, horiz=TRUE, bty="n")
legend(-180, 101, legend=KGcat[21:40,"KGcode"],col=KGrgbhex[21:40], pt.cex=2, pch=15, cex=0.6, horiz=TRUE, bty="n")
dev.off()

#Write netcdf file
write.KoeppenGeiger.netcdf(KGnum, fname="OUTPUT_FILE_NAME", varname="KG", undef=-1e30, description="CRU and GPCC ")


