#KG_run_template.R

#########################
#			#
# DO NOT EDIT THIS FILE #
#			#
#########################

source("utils_noSDMTools.R")
source("KoeppenGeiger.R")
library(rworldmap)

#Offline, make your input files:
#Temperature and precip files should be netcdf files, each with a variable of dimension (IM, JM, 12) for monthly values.


#Generate the classification

KGnum = run.KG(Tnc="TEMPERATURE_DATA",
	Pnc="PRECIPITATION_DATA",
	Tname="tmp",
	Pname="prec",
	IM=I_ARRAY_LEN, JM=J_ARRAY_LEN,
	ttext="TEMPERATURE_DATA", 
	ptext="PRECIPITATION_DATA",
	if.new=FALSE)


#Plot again without having to generate the classification all over.
plot.KG(KGnum)

#Write netcdf file
write.KoeppenGeiger.netcdf(KGnum, fname="OUTPUT_FILE_NAME", varname="KG", undef=-1e30, description="CRU and GPCC ")


